-- STEP 1: CREATE DATABASE
CREATE DATABASE IF NOT EXISTS alx_book_store;

-- STEP 2: SELECT DATABASE
USE alx_book_store;

-- STEP 3: CREATE Authors TABLE
CREATE TABLE Authors (
  AuthorId INT AUTO_INCREMENT PRIMARY KEY,
  AuthorName VARCHAR(215) NOT NULL
);

-- STEP 4: CREATE Books TABLE
CREATE TABLE Books (
  BookId INT AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(130) NOT NULL,
  AuthorId INT,
  Price DOUBLE,
  PublicationDate DATE,
  FOREIGN KEY (AuthorId) REFERENCES Authors(AuthorId)
);

-- STEP 5: CREATE Customers TABLE
CREATE TABLE Customers (
  CustomerId INT AUTO_INCREMENT PRIMARY KEY,
  CustomerName VARCHAR(215) NOT NULL,
  Email VARCHAR(215),
  Address TEXT
);

-- STEP 6: CREATE Orders TABLE
CREATE TABLE Orders (
  OrderId INT AUTO_INCREMENT PRIMARY KEY,
  CustomerId INT,
  OrderDate DATE,
  FOREIGN KEY (CustomerId) REFERENCES Customers(CustomerId)
);

-- STEP 7: CREATE OrderDetails TABLE
CREATE TABLE OrderDetails (
  OrderDetailId INT AUTO_INCREMENT PRIMARY KEY,
  OrderId INT,
  BookId INT,
  Quantity DOUBLE,
  FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
  FOREIGN KEY (BookId) REFERENCES Books(BookId)
);
